version: '3'
services:
  typescript-node-starter:
    container_name: typescript-node-starter
    image: typescript-node-starter
    command: sh docker-entrypoint.sh
    env_file:
      - docker-variables.env
    build:
      context: ./../
      dockerfile: Dockerfile
    volumes:
     - ./:/usr/src/app
    ports:
     - "3000:3000"