# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# on: push

name: Node.js CI

on: [push, pull_request]
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]



jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install
      working-directory: ./server
      run: npm i

    - name: alert
      run: echo "set working_dir"
      working-directory: ./server

    - name: getdir
      run: pwd
      working-directory: ./server

    - run: npm run build --if-present
      working-directory: ./server

    - run: npm test
      working-directory: ./server
