# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# on: push

name: cbg|test

on: [push, pull_request]
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

env:
  endpoint: http://xbot-d9fc7b57.localhost.run/webhooks/slack
  SLACK_ACCESS_TOKEN: xoxb-1220986307159-1242029704116-1E24WIyaQwv6dy1vWXLdLBFn
  SLACK_SIGNING_SECRET: 1790574d6c39f936b026ff7ff937b5e8
  PORT: 33010
  STATIC_SERVER: https://cbg.rik.ai/cdn/assets/
  STORYNAME: office
  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
  # SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:

    # - uses: act10ns/slack@v1
    #   with:
    #     status: starting
    #   if: always()

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install
      working-directory: ./server
      run: npm i

    # - name: alert-start
    #   run: echo "set working_dir"
    #   working-directory: ./server

    - name: getdir
      run: pwd
      working-directory: ./server

    - run: npm run build --if-present
      working-directory: ./server

    - run: npm test
      working-directory: ./server

    - name: slack notif
      uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
      if: always()
